/* Auto-generated by AuthSystem - 2026-05-22T04:55:48.383Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_46323b4e-c19',
  apiKey: 'ak_development_4590eba7d6bf13974305542234c4787f'
};
