/* Auto-generated by AuthSystem - 2026-05-22T05:05:40.568Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_46323b4e-c19',
  apiKey: 'ak_development_b7588ff5071fc4c36c848bc71cf0d7bf'
};
