/* Auto-generated by AuthSystem - 2026-05-26T02:34:48.746Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_46323b4e-c19',
  apiKey: 'ak_production_6c33c604ec43a455df80005fba2fb137'
};
