/* Auto-generated by AuthSystem - 2026-05-22T04:51:44.042Z */
import { createClient } from '@supabase/supabase-js';
import { requireSupabaseAnonKey, requireSupabaseUrl } from './supabaseRuntime';

export const supabase = createClient(requireSupabaseUrl(), requireSupabaseAnonKey());
