/* Auto-generated by AuthSystem - 2026-06-08T02:13:37.411Z */
import { createClient } from '@supabase/supabase-js';
import { requireSupabaseAnonKey, requireSupabaseUrl } from './supabaseRuntime';

export const supabase = createClient(requireSupabaseUrl(), requireSupabaseAnonKey());
